config/routes.rb
Tweetmark::Application.routes.draw do
    resources :users
    root to: 'static_pages#home'
    match '/about',   to: 'static_pages#about'
    match "/auth/:provider/callback" => "sessions#create"
    match "/signout" => "sessions#destroy", :as => :signout
    match '/tags/:hashtag' => "hashtags#hashtag"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TweetMark ©2012
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="http://natashatherobot.com/" target="_blank">NatashaTheRobot</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32449925-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "TweetMark", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right nav-pills">
          <% if current_user %>
			<li class="dropdown" id="menu1">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
		  			Welcome <%= current_user.name %>!
		        	<b class="caret"></b>
			    </a>
			  	<ul class="dropdown-menu">
		  			<li><a href='#'><%= link_to "Sign Out", signout_path %> </a></li>
		      	</ul>
		     </li>
			<% else %>
			<li><%= link_to "Sign in", "/auth/twitter" %></li>
		 <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
	<%= render 'layouts/googleanalytics'%>
  </head>
  <body>
     <%= render 'layouts/header' %>
	   <div class="container">
	     <%= yield %>
	     <%= render 'layouts/footer' %>
	   </div>
  </body>
</html>